In [1]:
from random import gauss
import os 
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from arch import arch_model
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf

In [4]:
current_dir = os.getcwd()
pickle_path = os.path.join(current_dir, 'data')
average_iv_series = pd.read_pickle(os.path.join(pickle_path,'Fulldataframesp500.pkl'))

In [5]:
average_iv_series

,date,forward_price,time_to_maturity,tau,risk_free_rate,is_call,strike_price,option_price,atm_price,moneyness,implied_volatility
16,2017-01-03,2256.207609,24,0.065753,0.008069,1,2145,115.20,2255.926204,0.950829,0.141237
17,2017-01-03,2256.207609,24,0.065753,0.008069,1,2150,110.50,2255.926204,0.953045,0.139715
18,2017-01-03,2256.207609,24,0.065753,0.008069,1,2155,105.85,2255.926204,0.955262,0.138392
19,2017-01-03,2256.207609,24,0.065753,0.008069,1,2160,101.25,2255.926204,0.957478,0.137197
20,2017-01-03,2256.207609,24,0.065753,0.008069,1,2165,96.70,2255.926204,0.959695,0.136073
...,...,...,...,...,...,...,...,...,...,...,...
3234875,2021-12-31,4762.933152,35,0.095890,0.005325,-1,4980,219.20,4763.575346,1.045433,0.524059
3234876,2021-12-31,4762.933152,35,0.095890,0.005325,-1,4985,223.75,4763.575346,1.046483,0.535061
3234877,2021-12-31,4762.933152,35,0.095890,0.005325,-1,4990,228.30,4763.575346,1.047533,0.546053
3234878,2021-12-31,4762.933152,35,0.095890,0.005325,-1,4995,232.95,4763.575346,1.048582,0.557209
3234879,2021-12-31,4762.933152,35,0.095890,0.005325,-1,5000,237.65,4763.575346,1.049632,0.568441